import java.io.FileNotFoundException;

// Исправил ошибки:
// 1. catch (Throwable ex) перенес ниже
// 2. throws FileNotFoundException можно убрать т.к. c информация с файла не считывается
// 3. throws Exception убрал, т.к. используется try catch

public class Main {

    public static void main(String[] args) {
        try {
            int a = 90;
            int b = 3;
            System.out.println(a / b);
            printSum(23, 234);
            int[] abc = {1, 2};
            abc[3] = 9;
        } catch (NullPointerException ex) {
            System.out.println("Указатель не может указывать на null!");
        } catch (IndexOutOfBoundsException ex) {
            System.out.println("Массив выходит за пределы своего размера!");
        } catch (Throwable ex) {
            System.out.println("Что-то пошло не так...");
        }
    }

    public static void printSum(Integer a, Integer b) {
        System.out.println(a + b);
    }
}
